const products=[{"cat":"推拉系列","name":"75 两轨断桥推拉窗","points":["两轨设计 · 紧凑实用","断桥型材 · 隔热保温","顺滑推拉 · 操作轻便"],"img":"images/image_18.webp"},{"cat":"推拉系列","name":"110 六轨断桥推拉 62 扇","points":["62 窄扇 · 极简线条","六轨结构 · 顺滑稳定","断桥型材 · 高效隔热"],"img":"images/image_19.webp"},{"cat":"推拉系列","name":"110 六轨断桥推拉 40 扇","points":["六轨结构 · 稳定顺滑","断桥隔热 · 节能环保","通透视野 · 现代极简"],"img":"images/image_20.webp"},{"cat":"推拉系列","name":"110 三轨断桥推拉系列","points":["三轨结构 · 稳定顺滑","断桥型材 · 节能静音","大视野通透 · 现代简约"],"img":"images/image_21.webp"},{"cat":"推拉系列","name":"100 三轨非断桥推拉窗","points":["三轨设计 · 经济实用","顺滑推拉 · 操作轻便","简约外观 · 高性价比"],"img":"images/image_22.webp"},{"cat":"推拉系列","name":"122 六轨断桥景观推拉窗","points":["六轨承载 · 宽幅通透","断桥节能 · 保温隔热","大视野景观 · 拥抱自然"],"img":"images/image_23.webp"},{"cat":"推拉系列","name":"122 六轨悬浮断桥推拉窗","points":["悬浮设计 · 轻盈通透","六轨结构 · 稳定顺滑","断桥型材 · 隔音隔热"],"img":"images/image_24.webp"},{"cat":"推拉系列","name":"128 六轨悬浮断桥推拉窗","points":["六轨悬浮设计 · 超大面积通透","断桥型材 · 隔音隔热出众","大玻璃景观视野 · 顺滑静音"],"img":"images/image_25.webp"},{"cat":"推拉系列","name":"128 六轨断桥景观推拉","points":["六轨结构 · 承重稳固","景观大玻璃 · 引景入室","断桥隔音 · 舒适静音体验"],"img":"images/image_26.webp"},{"cat":"平开系列","name":"110 断桥对开 · 外平开 · 下悬","points":["对开窗 · 视野开阔","外平开 + 下悬 · 灵活通风","下悬窗 + 回卷纱 · 实用防护"],"img":"images/image_27.webp"},{"cat":"平开系列","name":"110 断桥平开门 · 对开窗","points":["平开门 · 沉稳大气","断桥结构 · 密封保温","对开窗 · 通透采光"],"img":"images/image_28.webp"},{"cat":"重型门","name":"106 两轨重型门","points":["两轨结构 · 沉稳厚重","加厚型材 · 坚固耐用","超大视野 · 通透采光"],"img":"images/image_29.webp"},{"cat":"重型门","name":"125 两轨重型门","points":["两轨结构 · 宽幅通透","加厚型材 · 坚固耐用","大玻璃视野 · 现代大气"],"img":"images/image_30.webp"},{"cat":"重型门","name":"161 三轨重型推拉门","points":["三轨结构 · 稳固顺滑","重型型材 · 承重出色","宽幅玻璃 · 通透大气"],"img":"images/image_31.webp"},{"cat":"重型门","name":"190 三轨重型推拉门","points":["三轨结构 · 稳固顺滑","重型型材 · 承重出色","宽幅玻璃 · 通透大气"],"img":"images/image_32.webp"}];
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const body=document.body;
const header=document.getElementById('header');
const menuToggle=document.getElementById('menuToggle');
const mobileMenu=document.getElementById('mobileMenu');
let activeOverlay=null;
let lastFocused=null;

function syncBodyLock(){body.classList.toggle('overlay-open',Boolean(activeOverlay)||mobileMenu.classList.contains('open'));}
function setMenu(open){mobileMenu.classList.toggle('open',open);mobileMenu.setAttribute('aria-hidden',String(!open));menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'关闭导航菜单':'打开导航菜单');syncBodyLock();}
menuToggle.addEventListener('click',()=>setMenu(!mobileMenu.classList.contains('open')));
mobileMenu.addEventListener('click',e=>{if(e.target===mobileMenu||e.target.closest('a'))setMenu(false)});

function updateHeader(){header.classList.toggle('scrolled',window.scrollY>24)}
window.addEventListener('scroll',updateHeader,{passive:true});updateHeader();

const navMap={about:'about',catalog:'about',products:'products',standards:'standards',process:'cooperation',cooperation:'cooperation',contact:'contact'};
const navLinks=[...document.querySelectorAll('[data-nav]')];
const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;const key=navMap[visible.target.id]||visible.target.dataset.navSection||'';navLinks.forEach(a=>a.classList.toggle('active',a.dataset.nav===key));},{rootMargin:'-35% 0px -55% 0px',threshold:[0,.1,.25,.5]});
document.querySelectorAll('[data-nav-section],#about,#products,#standards,#cooperation,#contact').forEach(el=>observer.observe(el));

// Catalogue: manual navigation only, no auto-rotation.
(()=>{const box=document.getElementById('catalogShowcase'),track=document.getElementById('catalogTrack'),prev=document.getElementById('catalogPrev'),next=document.getElementById('catalogNext'),now=document.getElementById('catalogNow'),dots=document.getElementById('catalogDots');if(!box||!track)return;const slides=[...track.children];let index=0,touchX=null;slides.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.className='catalog-dot'+(i===0?' active':'');b.setAttribute('aria-label','查看第'+String(i+1).padStart(2,'0')+'页产品图册');b.addEventListener('click',()=>go(i));dots.appendChild(b)});const dotEls=[...dots.children];function render(){track.style.transform=`translateX(-${index*100}%)`;now.textContent=String(index+1).padStart(2,'0');dotEls.forEach((d,i)=>d.classList.toggle('active',i===index))}function go(i){index=(i+slides.length)%slides.length;render()}prev.addEventListener('click',()=>go(index-1));next.addEventListener('click',()=>go(index+1));box.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});box.addEventListener('touchend',e=>{if(touchX===null)return;const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>45)go(index+(dx<0?1:-1));touchX=null},{passive:true});render()})();

// Product filters, arrows, touch/mouse drag.
(()=>{const grid=document.getElementById('productGrid'),prev=document.getElementById('productPrev'),next=document.getElementById('productNext'),count=document.getElementById('productCount'),label=document.getElementById('productFilterLabel'),filters=[...document.querySelectorAll('.filter')];if(!grid)return;let filter='全部',pointerDown=false,dragging=false,startX=0,startScroll=0,suppressClick=false,pointerId=null;const visible=()=>[...grid.querySelectorAll('.product-card')].filter(c=>!c.hidden);function step(){const cards=visible();if(cards.length<2)return grid.clientWidth*.9;return Math.max(1,cards[1].getBoundingClientRect().left-cards[0].getBoundingClientRect().left)}function update(){const cards=visible();const g=grid.getBoundingClientRect();let best=0,dist=Infinity;cards.forEach((c,i)=>{const d=Math.abs(c.getBoundingClientRect().left-g.left);if(d<dist){dist=d;best=i}});count.textContent=String(Math.min(best+1,Math.max(cards.length,1))).padStart(2,'0')+' / '+String(cards.length).padStart(2,'0')}function move(dir){grid.scrollBy({left:dir*step(),behavior:reducedMotion?'auto':'smooth'});setTimeout(update,reducedMotion?0:320)}function apply(btn){filter=btn.dataset.filter;filters.forEach(b=>b.classList.toggle('active',b===btn));grid.querySelectorAll('.product-card').forEach(c=>c.hidden=filter!=='全部'&&c.dataset.cat!==filter);label.textContent=btn.textContent.trim()==='全部'?'全部产品':btn.textContent.trim();grid.scrollLeft=0;update()}filters.forEach(b=>b.addEventListener('click',()=>apply(b)));prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));grid.addEventListener('scroll',()=>requestAnimationFrame(update),{passive:true});grid.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointerDown=true;dragging=false;suppressClick=false;pointerId=e.pointerId;startX=e.clientX;startScroll=grid.scrollLeft});grid.addEventListener('pointermove',e=>{if(!pointerDown||e.pointerId!==pointerId||e.buttons!==1)return;const dx=e.clientX-startX;if(!dragging&&Math.abs(dx)>10){dragging=true;suppressClick=true;grid.classList.add('dragging');try{grid.setPointerCapture(pointerId)}catch{}}if(dragging){e.preventDefault();grid.scrollLeft=startScroll-dx}});function end(e){if(!pointerDown||e.pointerId!==pointerId)return;pointerDown=false;if(dragging){dragging=false;grid.classList.remove('dragging');try{grid.releasePointerCapture(pointerId)}catch{}update()}pointerId=null}grid.addEventListener('pointerup',end);grid.addEventListener('pointercancel',end);grid.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopPropagation();suppressClick=false}},true);update()})();

const productModal=document.getElementById('productModal'),modalCard=productModal.querySelector('.modal-card'),modalClose=document.getElementById('modalClose'),modalImg=document.getElementById('modalImg'),modalCat=document.getElementById('modalCat'),modalName=document.getElementById('modalName'),modalPoints=document.getElementById('modalPoints'),modalQuote=document.getElementById('modalQuote');
const leadQrModal=document.getElementById('leadQrModal'),leadCard=leadQrModal.querySelector('.modal-card'),leadClose=document.getElementById('leadQrClose'),leadDone=document.getElementById('leadQrDone');
function focusables(container){return [...container.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')]}
function openModal(modal,card){lastFocused=document.activeElement;activeOverlay=modal;modal.classList.add('open');modal.setAttribute('aria-hidden','false');syncBodyLock();requestAnimationFrame(()=>{(focusables(card)[0]||card).focus()})}
function closeModal(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');activeOverlay=null;syncBodyLock();if(lastFocused&&document.contains(lastFocused))lastFocused.focus()}
function trapTab(e,container){const f=focusables(container);if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}

function openProductCard(card){const p=products[Number(card.dataset.index)];modalImg.src=p.img;modalImg.alt=p.name+' 产品图片';modalCat.textContent=p.cat;modalName.textContent=p.name;modalPoints.innerHTML=p.points.map(x=>`<li>${x}</li>`).join('');openModal(productModal,modalCard)}
document.querySelectorAll('.product-card').forEach(card=>{card.addEventListener('click',()=>openProductCard(card));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProductCard(card)}})});
modalClose.addEventListener('click',()=>closeModal(productModal));modalQuote.addEventListener('click',()=>closeModal(productModal));productModal.addEventListener('click',e=>{if(e.target===productModal)closeModal(productModal)});
leadClose.addEventListener('click',()=>closeModal(leadQrModal));leadDone.addEventListener('click',()=>closeModal(leadQrModal));leadQrModal.addEventListener('click',e=>{if(e.target===leadQrModal)closeModal(leadQrModal)});

document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(activeOverlay)closeModal(activeOverlay);else if(mobileMenu.classList.contains('open'))setMenu(false)}if(e.key==='Tab'&&activeOverlay)trapTab(e,activeOverlay.querySelector('.modal-card'))});

const toast=document.getElementById('toast');let toastTimer;function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{}const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();let ok=false;try{ok=document.execCommand('copy')}catch{}area.remove();return ok}
document.getElementById('copyInquiry').addEventListener('click',async()=>{const type=document.getElementById('customerType').value,city=document.getElementById('city').value.trim()||'未填写',product=document.getElementById('wantProduct').value,need=document.getElementById('needType').value,extra=document.getElementById('extra').value.trim()||'暂无';const text=`【星力门窗 B端询价】
客户类型：${type}
所在城市：${city}
产品系列：${product}
需求类型：${need}
补充需求：${extra}`;const ok=await copyText(text);showToast(ok?'询价内容已复制，可直接发送给销售。':'已生成询价内容，请在弹窗中联系销售。');openModal(leadQrModal,leadCard)});

// AMap: desktop opens website; mobile uses official Web URI and requests native handoff.
(()=>{const map=document.getElementById('xingliAmapLink'),textLink=document.getElementById('amapTextLink');const ua=navigator.userAgent||'';const mobile=/Android|iPhone|iPad|iPod/i.test(ua)||(navigator.maxTouchPoints>1&&/Macintosh/i.test(ua));const mobileUrl='https://uri.amap.com/marker?poiid=B0LAGLRPAS&src=xingli-window&callnative=1';if(mobile){[map,textLink].forEach(a=>{a.href=mobileUrl;a.removeAttribute('target')})}})();
